-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}


profiles['sparks'] = S{
    'acheron shield',
    'koenig shield',
    'prize powder'
}

-- //sellnpc ore
profiles['ore'] = S{
    'iron ore',
    'copper ore',
    'tin ore',
    }

-- //sellnpc junk
profiles['junk'] = S{
    'chestnut',
    'san d\'Or. carrot',
    }

profiles['mog'] = S{
    'Beehive chip',
    'Kazham Peppers',
    'black pepper',
    'king truffle',
    'sage',
    'giant bird feather',
    'steel nugget',
    'fresh mugwort',
    'win. Tea leaves',
    'crawler egg',
    'crawler cocoon',
    'fresh marjoram',
    'rolanberry',
    'el. pachira fruit',
    'walnut',
    'coral fungus',
    'burdock',
    'popoto',
    'marguerite',
    'sunflower seeds',
    'tarutaru rice',
    'millioncorn',
    'kukuru bean',
    'frost turnip',
    'napa',

    'iron ore',
    'copper ore',
    'tin ore',
    'zinc Ore', 
    'flint stone',
    'bone chip',
    'bat fang',
    'beetle jaw',
    'scorpion claw',
    'snapping mole',
    'igneous rock',
    'meteorite',
    'fish bones',
    'insect wing',
    'scorpion shell',
    'H.Q. crab shell',
    'sheep tooth',
    'aht urhgan brass',
    'auric sand',
    'khroma ore',
    'dragon talon',
    'spider web',
    'gold ore',
    'mythril ore',
    'rock salt',

    'maple log',
    'arrowwood log',
    'walnut log',
    'oak log',
    'ebony log',
    'ash log',
    'chestnut log',
    'lacquer tree log',
    'mahogany log',
    'dogwood log',
    'red moko grass',
    'skull locust',
    'king locust',
    'lesser chigoe',
    'loc. elutriator',
    'felicifruit',
    'moko grass',
    'dryad root',
    'mushroom locust',
    'eggplant',
    'pamamas',
    'blue peas',
    'san d\'Or. Flour',
    'ginger',
    
    'chestnut',
    'flax flower',
    'pine nuts',
    'Deathball',
    'mhaura garlic',
    'vanilla',
    'holy basil',
    'la theine cbg.',
    'saruta cotton',
    'habaneros',
    'vomp carrot',
    'foulwth. frog',
    'kitron',
    'faerie apple',
    'yagudo cherry',
    'lilac',
    'orange juice',
    'woozyshroom',
    'wild onion',
    'almond',
    'Ameretat Vine',
    'puffball',
    'winterflower',
    'pugil scales',

    'soil geode',
    'ifritite',
    'titanite',
    'leviatite',

    'walnut log',

    'Rusty Bucket',
    'zebra eel',
    'gugru tuna',
    'shall shell',
    'Contortopus',
    'Black Prawn',
    'black eel',
    'giant catfish',
    'yayinbaligi',
    'ca cuong',
    'moat carp',
    'cobalt jellyfish',
    'elshimo newt',
    'moorish idol',
    'cone calamary',
    'red terrapin',
    'mackerel',
    'crescent fish',
    'bastore bream',
    'bluetail',
    'copper frog',
    'dark bass',
    'pipira',
    'adoulinian kelp',
    'quus',
    'barnacle',
    'senroh sardine',
    'ulbukan lobster',
    'crayfish',
    'black sole',
    'gigant squid',
    'three-eyed fish',
    'gold carp',
    'grimmonite',
    'red rose',
    'gavial fish',
    'black ghost',
    'brass loach',
    'hi-ether',
    'elm log',
    'kapor log',
    'crab shell',
    'gysahl greens',
    'zegham carrot',
    'purple polypore',
    'giant stinger',
    'sprig of chamomile',
    'eastern ginger root',
    'acorn',
    'pebble',
    'distilled water',

    'flame geode',
    'snow geode',
    'breeze geode',
    'soil geode',
    'thunder geode',
    'aqua geode',
    'light geode',
    'shadow geode',
    'wijnruit',
    'handful of bay leaves',
    'sweet william',
    'Kopparnickel Ore',
    'salted hare',

    'ramuite',
    'garudite',
    'carbite',
    'leviatite',

    'smilodon hide',
    'durium sheet'

}

return profiles
